version: '3'

services:

  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    networks:
      - external
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  misp-instance-A:
    image: hackinglab/misp
    container_name: misp-instance-A
    restart: unless-stopped
    depends_on:
      - database-instance-A
    networks:
      - external
      - internal-instance-A
    ports: 
      - "10000:80"
    volumes:
      - ./data-instance-A/misp:/var/www/MISP:rw
      - ./data-shared:/data-shared:rw
    environment:
      - MYSQL_HOST=database-instance-A
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MISP_ADMIN_EMAIL=${MISP_ADMIN_EMAIL}
      - MISP_ADMIN_PASSPHRASE=${MISP_ADMIN_PASSPHRASE}
      - MISP_BASEURL=http://instance-a.misp.localhost
      - POSTFIX_RELAY_HOST=${POSTFIX_RELAY_HOST}
      - TIMEZONE=${TIMEZONE}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.misp-a.rule=Host(`instance-a.misp.localhost`)"
      - "traefik.http.routers.misp-a.service=misp-a"
      - "traefik.http.services.misp-a.loadbalancer.server.port=80"

  misp-instance-B:
    image: hackinglab/misp
    container_name: misp-instance-B
    restart: unless-stopped
    depends_on:
      - database-instance-B
    networks:
      - external
      - internal-instance-B
    ports: 
      - "11000:80"
    volumes:
      - ./data-instance-B/misp:/var/www/MISP:rw
      - ./data-shared:/data-shared:rw
    environment:
      - MYSQL_HOST=database-instance-B
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MISP_ADMIN_EMAIL=${MISP_ADMIN_EMAIL}
      - MISP_ADMIN_PASSPHRASE=${MISP_ADMIN_PASSPHRASE}
      - MISP_BASEURL=http://instance-b.misp.localhost
      - POSTFIX_RELAY_HOST=${POSTFIX_RELAY_HOST}
      - TIMEZONE=${TIMEZONE}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.misp-b.rule=Host(`instance-b.misp.localhost`)"
      - "traefik.http.routers.misp-b.service=misp-b"
      - "traefik.http.services.misp-b.loadbalancer.server.port=80"

  misp-instance-E:
    image: hackinglab/misp
    container_name: misp-instance-E
    restart: unless-stopped
    depends_on:
      - database-instance-E
    networks:
      - external
      - internal-instance-E
    ports: 
      - "12000:80"
    volumes:
      - ./data-instance-E/misp:/var/www/MISP:rw
      - ./data-shared:/data-shared:rw
    environment:
      - MYSQL_HOST=database-instance-E
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MISP_ADMIN_EMAIL=${MISP_ADMIN_EMAIL}
      - MISP_ADMIN_PASSPHRASE=${MISP_ADMIN_PASSPHRASE}
      - MISP_BASEURL=http://instance-e.misp.localhost
      - POSTFIX_RELAY_HOST=${POSTFIX_RELAY_HOST}
      - TIMEZONE=${TIMEZONE}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.misp-e.rule=Host(`instance-e.misp.localhost`)"
      - "traefik.http.routers.misp-e.service=misp-e"
      - "traefik.http.services.misp-e.loadbalancer.server.port=80"

  database-instance-A:
    image: mysql/mysql-server:5.7
    container_name: database-instance-A
    restart: unless-stopped
    networks:
      - internal-instance-A
    volumes:
      - ./data-instance-A/database:/var/lib/mysql:rw
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  
  database-instance-B:
    image: mysql/mysql-server:5.7
    container_name: database-instance-B
    restart: unless-stopped
    networks:
      - internal-instance-B
    volumes:
      - ./data-instance-B/database:/var/lib/mysql:rw
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  
  database-instance-E:
    image: mysql/mysql-server:5.7
    container_name: database-instance-E
    restart: unless-stopped
    networks:
      - internal-instance-E
    volumes:
      - ./data-instance-E/database:/var/lib/mysql:rw
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

networks:
  external:
    name: external-network
    driver: bridge
  internal-instance-A:
    name: internal-instance-A
    driver: bridge
    internal: true
  internal-instance-B:
    name: internal-instance-B
    driver: bridge
    internal: true
  internal-instance-E:
    name: internal-instance-E
    driver: bridge
    internal: true