version: '3'

services:

  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    command:
      - "--log.level=FATAL"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"

    networks:
      - internal-all-instances
      - internal-instance-default
      - internal-instance-A
      - internal-instance-B
      - internal-instance-E
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  errorservice:
    build: 
      context: ./misp/traefik-custom-error-pages
    networks:
      - internal-all-instances
      - internal-instance-default
      - internal-instance-A
      - internal-instance-B
      - internal-instance-E
    labels:
          - "traefik.enable=true"
          - "traefik.http.routers.error.rule=Host(`error.localhost`)"
          - "traefik.http.routers.error.service=errorservice"
          - "traefik.http.services.errorservice.loadbalancer.server.port=80"
          - "traefik.http.routers.error.entrypoints=web"    

  misp-instance-default:
    image: hackinglab/misp:latest
    container_name: misp-instance-default
    restart: unless-stopped
    depends_on:
      - database-instance-default
    networks:
      - internal-all-instances
      - internal-instance-default
    volumes:
      - ./data-instance-default/misp:/var/www/MISP:rw
      - ./data-shared:/data-shared:rw
    environment:
      - MYSQL_HOST=${MYSQL_HOST_DEFAULT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MISP_ADMIN_EMAIL=${MISP_ADMIN_EMAIL}
      - MISP_ADMIN_PASSPHRASE=${MISP_ADMIN_PASSPHRASE}
      - INSTANCE_TAG=${INSTANCE_DEFAULT_TAG}
      - POSTFIX_RELAY_HOST=${POSTFIX_RELAY_HOST}
      - TIMEZONE=${TIMEZONE}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.misp-default.rule=Host(`${INSTANCE_DEFAULT_URL}`)"
      - "traefik.http.routers.misp-default.middlewares=test-errorpages"
      - "traefik.http.middlewares.test-errorpages.errors.status=500-599"
      - "traefik.http.middlewares.test-errorpages.errors.service=errorservice"
      - "traefik.http.middlewares.test-errorpages.errors.query=/inprogress.html"
    ports: 
      - "10000:80"
      
  misp-instance-A:
    image: hackinglab/misp:latest
    container_name: misp-instance-A
    restart: unless-stopped
    depends_on:
      - database-instance-A
    networks:
      - internal-all-instances
      - internal-instance-A
    volumes:
      - ./data-instance-A/misp:/var/www/MISP:rw
      - ./data-shared:/data-shared:rw
    environment:
      - MYSQL_HOST=${MYSQL_HOST_A}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MISP_ADMIN_EMAIL=${MISP_ADMIN_EMAIL}
      - MISP_ADMIN_PASSPHRASE=${MISP_ADMIN_PASSPHRASE}
      - INSTANCE_TAG=${INSTANCE_A_TAG}
      - POSTFIX_RELAY_HOST=${POSTFIX_RELAY_HOST}
      - TIMEZONE=${TIMEZONE}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.misp-a.rule=Host(`${INSTANCE_A_URL}`)"
      - "traefik.http.routers.misp-a.middlewares=test-errorpages"
      - "traefik.http.middlewares.test-errorpages.errors.status=500-599"
      - "traefik.http.middlewares.test-errorpages.errors.service=errorservice"
      - "traefik.http.middlewares.test-errorpages.errors.query=/inprogress.html"


  misp-instance-B:
    image: hackinglab/misp:latest
    container_name: misp-instance-B
    restart: unless-stopped
    depends_on:
      - database-instance-B
    networks:
      - internal-all-instances
      - internal-instance-B
    volumes:
      - ./data-instance-B/misp:/var/www/MISP:rw
      - ./data-shared:/data-shared:rw
    environment:
      - MYSQL_HOST=${MYSQL_HOST_B}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MISP_ADMIN_EMAIL=${MISP_ADMIN_EMAIL}
      - MISP_ADMIN_PASSPHRASE=${MISP_ADMIN_PASSPHRASE}
      - INSTANCE_TAG=${INSTANCE_B_TAG}
      - POSTFIX_RELAY_HOST=${POSTFIX_RELAY_HOST}
      - TIMEZONE=${TIMEZONE}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.misp-b.rule=Host(`${INSTANCE_B_URL}`)"
      - "traefik.http.routers.misp-b.middlewares=test-errorpages"
      - "traefik.http.middlewares.test-errorpages.errors.status=500-599"
      - "traefik.http.middlewares.test-errorpages.errors.service=errorservice"
      - "traefik.http.middlewares.test-errorpages.errors.query=/inprogress.html"


  misp-instance-E:
    image: hackinglab/misp:latest
    container_name: misp-instance-E
    restart: unless-stopped
    depends_on:
      - database-instance-E
    networks:
      - internal-all-instances
      - internal-instance-E
    volumes:
      - ./data-instance-E/misp:/var/www/MISP:rw
      - ./data-shared:/data-shared:rw
    environment:
      - MYSQL_HOST=${MYSQL_HOST_E}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MISP_ADMIN_EMAIL=${MISP_ADMIN_EMAIL}
      - MISP_ADMIN_PASSPHRASE=${MISP_ADMIN_PASSPHRASE}
      - INSTANCE_TAG=${INSTANCE_E_TAG}
      - POSTFIX_RELAY_HOST=${POSTFIX_RELAY_HOST}
      - TIMEZONE=${TIMEZONE}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.misp-e.rule=Host(`${INSTANCE_E_URL}`)"
      - "traefik.http.routers.misp-e.middlewares=test-errorpages"
      - "traefik.http.middlewares.test-errorpages.errors.status=500-599"
      - "traefik.http.middlewares.test-errorpages.errors.service=errorservice"
      - "traefik.http.middlewares.test-errorpages.errors.query=/inprogress.html"


  database-instance-default:
    image: mysql/mysql-server:5.7
    container_name: database-instance-default
    restart: unless-stopped
    networks:
      - internal-instance-default
    volumes:
      - ./data-instance-default/database:/var/lib/mysql:rw
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  
  database-instance-A:
    image: mysql/mysql-server:5.7
    container_name: database-instance-A
    restart: unless-stopped
    networks:
      - internal-instance-A
    volumes:
      - ./data-instance-A/database:/var/lib/mysql:rw
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  
  database-instance-B:
    image: mysql/mysql-server:5.7
    container_name: database-instance-B
    restart: unless-stopped
    networks:
      - internal-instance-B
    volumes:
      - ./data-instance-B/database:/var/lib/mysql:rw
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  
  database-instance-E:
    image: mysql/mysql-server:5.7
    container_name: database-instance-E
    restart: unless-stopped
    networks:
      - internal-instance-E
    volumes:
      - ./data-instance-E/database:/var/lib/mysql:rw
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

networks:
  internal-all-instances:
    name: internal-all-instances
    driver: bridge
    internal: false
  internal-instance-default:
    name: internal-instance-default
    driver: bridge
    internal: false
  internal-instance-A:
    name: internal-instance-A
    driver: bridge
    internal: false
  internal-instance-B:
    name: internal-instance-B
    driver: bridge
    internal: false
  internal-instance-E:
    name: internal-instance-E
    driver: bridge
    internal: false
    
