
name: Build and Push to Docker Hub

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: janiswolfost
        DOCKER_HUB_TOKEN: 466fb3a5-549a-4324-91e7-52225e30363e
        
      run : docker login -u $DOCKER_USER - p $DOCKER_HUB_TOKEN
      
    - name: Build docker image
      run: docker build ./misp/. --file Dockerfile --tag hl/misp-docker-image:$(date +%s)
      
    - name: Docker push
      run: docker push janiswolfost/hl

