name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build container image
      # run: cd ./misp/ && docker build . --file Dockerfile --tag misp-docker:$(date +%s) --tag misp-docker:latest
      run: cd ./misp/ && docker build . --file Dockerfile --tag test
    
    - name: Log into github container registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
      
    - name: push image go github container registry
      run: | 
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/test:${{ github.run_id }}
        docker push test
      
