# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image

on:
  push:
    branches: [main]

env:
  dockerhub_image_name: misp
  dockerhub_username: janiswolfost
  dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
  #dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
  #dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ env.dockerhub_username }}
          password: 466fb3a5-549a-4324-91e7-52225e30363e
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.dockerhub_username }}/${{ env.dockerhub_image_name }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./misp/.
          push: true
          #tags: ${{ steps.meta.outputs.tags }}
          tags: ${{ env.dockerhub_username }}/${{ env.dockerhub_image_name }}:latest,${{ env.dockerhub_username }}/${{ env.dockerhub_image_name }}:${{ github.JOB }}
          labels: ${{ steps.meta.outputs.labels }}
