# https://github.com/marketplace/actions/build-and-push-docker-images

name: Build and Push to Docker Hub

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: janiswolfost
          password: 466fb3a5-549a-4324-91e7-52225e30363e
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: /misp/.
          push: true
          tags: user/app:latest
